/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FeedPost {
  'id' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'caption' : [] | [string],
  'image' : ExternalBlob,
}
export interface FriendRequests {
  'incoming' : Array<Principal>,
  'outgoing' : Array<Principal>,
}
export interface Message {
  'status' : MessageStatus,
  'content' : MessageContent,
}
export interface MessageContent {
  'video' : [] | [ExternalBlob],
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
  'photo' : [] | [ExternalBlob],
}
export type MessageStatus = { 'deleted' : null } |
  { 'normal' : null } |
  { 'edited' : null };
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'recipient' : Principal,
  'isRead' : boolean,
  'sender' : [] | [Principal],
  'message' : string,
  'timestamp' : bigint,
  'senderName' : [] | [string],
  'relatedPostId' : [] | [string],
}
export type NotificationType = { 'friendAccepted' : null } |
  { 'like' : null } |
  { 'postShared' : null } |
  { 'comment' : null } |
  { 'message' : null } |
  { 'friendRequest' : null };
export interface Reel {
  'id' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'caption' : [] | [string],
  'videoUrl' : ExternalBlob,
}
export interface SimplifiedUserProfile {
  'principal' : Principal,
  'userId' : string,
  'name' : string,
  'isPublic' : boolean,
  'displayPic' : [] | [ExternalBlob],
}
export interface UserProfile {
  'bio' : string,
  'userId' : string,
  'name' : string,
  'isPublic' : boolean,
  'displayPic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addCommentToPost' : ActorMethod<[string, string], undefined>,
  'addCommentToReel' : ActorMethod<[string, string], undefined>,
  'adminDeleteAccount' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelFriendRequest' : ActorMethod<[string], undefined>,
  'checkIfFriends' : ActorMethod<[Principal, Principal], boolean>,
  'createPost' : ActorMethod<[ExternalBlob, [] | [string]], FeedPost>,
  'createReel' : ActorMethod<[ExternalBlob, [] | [string]], Reel>,
  'declineFriendRequest' : ActorMethod<[Principal], undefined>,
  'deleteAccount' : ActorMethod<[], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteReel' : ActorMethod<[string], undefined>,
  'editMessage' : ActorMethod<[bigint, string], undefined>,
  'getAllPosts' : ActorMethod<[], Array<FeedPost>>,
  'getAllReels' : ActorMethod<[], Array<Reel>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFriendRequests' : ActorMethod<[], FriendRequests>,
  'getFriends' : ActorMethod<[Principal], Array<Principal>>,
  'getFriendsList' : ActorMethod<[], Array<Principal>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingRequests' : ActorMethod<[Principal], Array<Principal>>,
  'getPostById' : ActorMethod<[string], [] | [FeedPost]>,
  'getPostCommentCount' : ActorMethod<[string], bigint>,
  'getPostLikeCount' : ActorMethod<[string], bigint>,
  'getPostsByAuthor' : ActorMethod<[Principal], Array<FeedPost>>,
  'getReelById' : ActorMethod<[string], [] | [Reel]>,
  'getReelCommentCount' : ActorMethod<[string], bigint>,
  'getReelLikeCount' : ActorMethod<[string], bigint>,
  'getReelsByAuthor' : ActorMethod<[Principal], Array<Reel>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByUserId' : ActorMethod<[string], [] | [UserProfile]>,
  'hasProfile' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'likeReel' : ActorMethod<[string], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProfiles' : ActorMethod<[string], Array<SimplifiedUserProfile>>,
  'sendFriendRequest' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<
    [Principal, string, [] | [ExternalBlob], [] | [ExternalBlob]],
    bigint
  >,
  'unfriend' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'unlikeReel' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];