/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FeedPost = IDL.Record({
  'id' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'caption' : IDL.Opt(IDL.Text),
  'image' : ExternalBlob,
});
export const Reel = IDL.Record({
  'id' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'caption' : IDL.Opt(IDL.Text),
  'videoUrl' : ExternalBlob,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'isPublic' : IDL.Bool,
  'displayPic' : IDL.Opt(ExternalBlob),
});
export const MessageStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'normal' : IDL.Null,
  'edited' : IDL.Null,
});
export const MessageContent = IDL.Record({
  'video' : IDL.Opt(ExternalBlob),
  'text' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Message = IDL.Record({
  'status' : MessageStatus,
  'content' : MessageContent,
});
export const NotificationType = IDL.Variant({
  'friendAccepted' : IDL.Null,
  'like' : IDL.Null,
  'postShared' : IDL.Null,
  'comment' : IDL.Null,
  'message' : IDL.Null,
  'friendRequest' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'sender' : IDL.Opt(IDL.Principal),
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Opt(IDL.Text),
  'relatedPostId' : IDL.Opt(IDL.Text),
});
export const SimplifiedUserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'isPublic' : IDL.Bool,
  'displayPic' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addCommentToPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addCommentToReel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminDeleteAccount' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelFriendRequest' : IDL.Func([IDL.Text], [], []),
  'createPost' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [FeedPost], []),
  'createReel' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [Reel], []),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'deleteAccount' : IDL.Func([], [], []),
  'deleteMessage' : IDL.Func([IDL.Int], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteReel' : IDL.Func([IDL.Text], [], []),
  'editMessage' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(FeedPost)], ['query']),
  'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(FeedPost)], ['query']),
  'getPostCommentCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostsByAuthor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FeedPost)],
      ['query'],
    ),
  'getReelById' : IDL.Func([IDL.Text], [IDL.Opt(Reel)], ['query']),
  'getReelCommentCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getReelLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getReelsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Reel)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUserId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'likeReel' : IDL.Func([IDL.Text], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProfiles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SimplifiedUserProfile)],
      ['query'],
    ),
  'sendFriendRequest' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [IDL.Int],
      [],
    ),
  'unfriend' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'unlikeReel' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FeedPost = IDL.Record({
    'id' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'caption' : IDL.Opt(IDL.Text),
    'image' : ExternalBlob,
  });
  const Reel = IDL.Record({
    'id' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'caption' : IDL.Opt(IDL.Text),
    'videoUrl' : ExternalBlob,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'isPublic' : IDL.Bool,
    'displayPic' : IDL.Opt(ExternalBlob),
  });
  const MessageStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'normal' : IDL.Null,
    'edited' : IDL.Null,
  });
  const MessageContent = IDL.Record({
    'video' : IDL.Opt(ExternalBlob),
    'text' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Message = IDL.Record({
    'status' : MessageStatus,
    'content' : MessageContent,
  });
  const NotificationType = IDL.Variant({
    'friendAccepted' : IDL.Null,
    'like' : IDL.Null,
    'postShared' : IDL.Null,
    'comment' : IDL.Null,
    'message' : IDL.Null,
    'friendRequest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'sender' : IDL.Opt(IDL.Principal),
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Opt(IDL.Text),
    'relatedPostId' : IDL.Opt(IDL.Text),
  });
  const SimplifiedUserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'isPublic' : IDL.Bool,
    'displayPic' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addCommentToPost' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addCommentToReel' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminDeleteAccount' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelFriendRequest' : IDL.Func([IDL.Text], [], []),
    'createPost' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [FeedPost], []),
    'createReel' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [Reel], []),
    'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'deleteAccount' : IDL.Func([], [], []),
    'deleteMessage' : IDL.Func([IDL.Int], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteReel' : IDL.Func([IDL.Text], [], []),
    'editMessage' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(FeedPost)], ['query']),
    'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPostById' : IDL.Func([IDL.Text], [IDL.Opt(FeedPost)], ['query']),
    'getPostCommentCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostsByAuthor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FeedPost)],
        ['query'],
      ),
    'getReelById' : IDL.Func([IDL.Text], [IDL.Opt(Reel)], ['query']),
    'getReelCommentCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getReelLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getReelsByAuthor' : IDL.Func([IDL.Principal], [IDL.Vec(Reel)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUserId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'likeReel' : IDL.Func([IDL.Text], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProfiles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SimplifiedUserProfile)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [IDL.Int],
        [],
      ),
    'unfriend' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'unlikeReel' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };